# Generated by Django 4.1.7 on 2024-10-06 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Model',
            fields=[
                ('Admin_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=50)),
                ('Last_Logged_In', models.DateField(default=django.utils.timezone.now)),
                ('Last_Activity', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Category_Model',
            fields=[
                ('Category_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Category_Name', models.CharField(max_length=100)),
                ('Category_Description', models.CharField(max_length=100)),
                ('Date_Created', models.DateField()),
                ('Status', models.CharField(max_length=50)),
                ('Admin_Id', models.ForeignKey(db_column='Admin_Id', on_delete=django.db.models.deletion.CASCADE, to='CareCollective.admin_model')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Donor_Model',
            fields=[
                ('Donor_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Donation_History_Count', models.IntegerField(default=0)),
                ('Verified_Date', models.DateField(default=django.utils.timezone.now)),
                ('Last_Donation_Date', models.DateField(blank=True, null=True)),
                ('Preferred_Donation_Categories', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'donor',
            },
        ),
        migrations.CreateModel(
            name='Item_Model',
            fields=[
                ('Item_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Item_Name', models.CharField(max_length=100)),
                ('Item_Description', models.CharField(max_length=300)),
                ('Quantity', models.IntegerField(default=1)),
                ('Expiry_Date', models.DateField(blank=True, null=True)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Status', models.CharField(max_length=50)),
                ('Category_Id', models.ForeignKey(db_column='Category_Id', on_delete=django.db.models.deletion.CASCADE, to='CareCollective.category_model')),
                ('Donor_Id', models.ForeignKey(db_column='Donor_Id', on_delete=django.db.models.deletion.CASCADE, to='CareCollective.donor_model')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='State_Model',
            fields=[
                ('State_Id', models.AutoField(primary_key=True, serialize=False)),
                ('State_Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'states_of_india',
            },
        ),
        migrations.CreateModel(
            name='Users_Model',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Mobile_Number', models.CharField(max_length=10)),
                ('Email_Id', models.EmailField(max_length=100)),
                ('Date_Of_Join', models.DateField(default=django.utils.timezone.now)),
                ('Admin_Flag', models.CharField(default='False', max_length=20)),
                ('Status', models.CharField(default='Active', max_length=10)),
                ('State_Id', models.ForeignKey(db_column='State_Id', on_delete=django.db.models.deletion.RESTRICT, to='CareCollective.state_model')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Request_Model',
            fields=[
                ('Request_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(default=1)),
                ('Request_Date', models.DateField()),
                ('Urgency', models.CharField(max_length=100)),
                ('Reason', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=50)),
                ('Donor_Id', models.ForeignKey(db_column='Donor_Id', on_delete=django.db.models.deletion.CASCADE, to='CareCollective.donor_model')),
                ('Item_Id', models.ForeignKey(db_column='Item_Id', on_delete=django.db.models.deletion.CASCADE, to='CareCollective.item_model')),
                ('UID', models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.CASCADE, to='CareCollective.users_model')),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='Maps_Model',
            fields=[
                ('Map_Id', models.AutoField(primary_key=True, serialize=False)),
                ('City', models.CharField(max_length=100)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Map_URL', models.URLField(blank=True, max_length=500, null=True)),
                ('Created_Date', models.DateField(default=django.utils.timezone.now)),
                ('State_Id', models.ForeignKey(db_column='State_Id', on_delete=django.db.models.deletion.CASCADE, to='CareCollective.state_model')),
            ],
            options={
                'db_table': 'location_maps',
            },
        ),
        migrations.CreateModel(
            name='Login_Model',
            fields=[
                ('Login_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('UID', models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.CASCADE, to='CareCollective.users_model')),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.AddField(
            model_name='donor_model',
            name='UID',
            field=models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.CASCADE, to='CareCollective.users_model'),
        ),
        migrations.CreateModel(
            name='Chat_Model',
            fields=[
                ('Message_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.CharField(max_length=100)),
                ('Sent_By', models.IntegerField()),
                ('Message_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Donor_Id', models.ForeignKey(db_column='Donor_Id', on_delete=django.db.models.deletion.RESTRICT, to='CareCollective.donor_model')),
                ('UID', models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.RESTRICT, to='CareCollective.users_model')),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
        migrations.AddField(
            model_name='category_model',
            name='Donor_Id',
            field=models.ForeignKey(db_column='Donor_Id', on_delete=django.db.models.deletion.CASCADE, to='CareCollective.donor_model'),
        ),
        migrations.AddField(
            model_name='admin_model',
            name='UID',
            field=models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.CASCADE, to='CareCollective.users_model'),
        ),
    ]
