# Generated by Django 4.1.7 on 2024-10-21 17:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CareCollective', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_Model',
            fields=[
                ('Comment_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Comment', models.CharField(max_length=100)),
                ('Comment_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Donor_Id', models.ForeignKey(db_column='Donor_Id', on_delete=django.db.models.deletion.RESTRICT, to='CareCollective.donor_model')),
                ('UID', models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.RESTRICT, to='CareCollective.users_model')),
            ],
            options={
                'db_table': 'user_comments',
            },
        ),
    ]
